Repository daqifi/daqifi-desktop, pull requests merged in 2025-08, with the labels that each got.

#177 chore: add .gitattributes for consistent line endings
  .gitattributes
Labels: Review effort 1/5

#181 feat: Show device information in USB view (#104)
  Daqifi.Desktop/Device/AbstractStreamingDevice.cs
  Daqifi.Desktop/Device/SerialDevice/SerialDeviceFinder.cs
  Daqifi.Desktop/Device/SerialDevice/SerialStreamingDevice.cs
  Daqifi.Desktop/View/ConnectionDialog.xaml
Labels: Review effort 4/5

#189 "Claude PR Assistant workflow"
  .github/workflows/claude.yml
Labels: Review effort 2/5, Possible security concern

#190 feat: add delay and re-enable WiFi after network configuration change…
  Daqifi.Desktop/Device/AbstractStreamingDevice.cs
  Daqifi.Desktop/Device/HidDevice/HidFirmwareDevice.cs
  Daqifi.Desktop/Device/IStreamingDevice.cs
  Daqifi.Desktop/View/DeviceLogsView.xaml
  Daqifi.Desktop/View/DeviceLogsView.xaml.cs
  Daqifi.Desktop/ViewModels/DaqifiViewModel.cs
  Daqifi.Desktop/ViewModels/DeviceLogsViewModel.cs
Labels: Review effort 2/5

#191 fix: firmware notification are fixed
  Daqifi.Desktop.Test/Helpers/VersionHelperTests.cs
  Daqifi.Desktop.Test/Loggers/FirmwareUpdatationManagerTests.cs
  Daqifi.Desktop/Helpers/VersionHelper.cs
  Daqifi.Desktop/Loggers/FirmwareUpdatationManager.cs
  Daqifi.Desktop/MainWindow.xaml
  Daqifi.Desktop/ViewModels/DaqifiViewModel.cs
Labels: Review effort 3/5

#206 chore: update dependabot PR prefix to 'deps: '
  .github/dependabot.yml
Labels: Review effort 1/5

#222 deps: Update Entity Framework Core to 9.0.8
  Daqifi.Desktop.Common/Daqifi.Desktop.Common.csproj
  Daqifi.Desktop.Common/Loggers/AppLogger.cs
  Daqifi.Desktop.IO/Daqifi.Desktop.IO.csproj
  Daqifi.Desktop.Test/Daqifi.Desktop.Test.csproj
  Daqifi.Desktop/Daqifi.Desktop.csproj
Labels: Review effort 2/5

#228 deps: Update development tools and testing framework dependencies
  Daqifi.Desktop.Bootloader.Test/Daqifi.Desktop.Bootloader.Test.csproj
  Daqifi.Desktop.Bootloader/Daqifi.Desktop.Bootloader.csproj
  Daqifi.Desktop.Common.Test/Daqifi.Desktop.Common.Test.csproj
  Daqifi.Desktop.Common/Daqifi.Desktop.Common.csproj
  Daqifi.Desktop.DataModel.Test/Daqifi.Desktop.DataModel.Test.csproj
  Daqifi.Desktop.DataModel/Daqifi.Desktop.DataModel.csproj
  Daqifi.Desktop.IO.Test/Daqifi.Desktop.IO.Test.csproj
  Daqifi.Desktop.IO/Daqifi.Desktop.IO.csproj
  Daqifi.Desktop.Test/Daqifi.Desktop.Test.csproj
  Daqifi.Desktop/Daqifi.Desktop.csproj
Labels: Review effort 2/5
